#pragma config(Sensor, in8,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, limitSwitch,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task stopAllMotors(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[armMotor] = 0;
	motor[clawMotor] = 0;
}
task LCD()
{
  clearLCDLine(0);
  clearLCDLine(1);

  bLCDBacklight = true;
  displayLCDPos(0,1);
  displayNextLCDString("Verkefni nr: 4");

  displayLCDPos(1,1);
  displayNextLCDString("Version 1.0.0");
}

task sonar(){
		if(SensorValue(lightSensor) > 300){
			StartTask(stopAllMotors);
		}
		else if(SensorValue(sonarSensor) > 10  || SensorValue(sonarSensor) == -1)
		{
			motor[rightMotor] = 63;
			motor[leftMotor]  = 63;
		}
		else{
			StartTask(stopAllMotors);
		}
}

task main()
{
  StartTask(LCD);
	while (SensorValue[pushBtn] == 0 && vexRT[Btn7U] == 0){
		StartTask(sonar);
	}
	StartTask(stopAllMotors);
}
