#pragma config(Sensor, dgtl6,  pushBtn,        sensorTouch)
#pragma config(Sensor, dgtl11, limitSwitch,    sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           clawMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 50;

task stopAllMotors(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[armMotor] = 0;
	motor[clawMotor] = 0;
}

task drive(){
	if(abs(vexRT[Ch1]) > threshold)         // If the left joystick is greater than or less than the threshold:
    {
			motor[rightMotor] = (vexRT[Ch1] / -1) / 2;
			motor[leftMotor] = vexRT[Ch1] / 2;
		}
		else                                    // If the left joystick is within the threshold:
    {
      motor[leftMotor]  = 0;
     	motor[rightMotor] = 0;    // Stop the left motor (cancel noise)
    }
		if(abs(vexRT[Ch2]) > threshold)         // If the left joystick is greater than or less than the threshold:
    {
			motor[leftMotor] = vexRT[Ch2] / 2;
			motor[rightMotor] = vexRT[Ch2] / 2;
		}
		else{
			motor[leftMotor]  = 0;
     	motor[rightMotor] = 0;
    }
  }

task main()
{
	while (SensorValue[pushBtn] == 0 && vexRT[Btn7U] == 0){

		StartTask(drive);


		if(vexRT[Btn5D] == 1)
		{
			if(SensorValue[limitSwitch] == 0){
				motor[armMotor] = 60;
			}
		}
		else if(vexRT[Btn5U] == 1)
		{
				motor[armMotor] = -60;
		}
		else
		{
			motor[armMotor] = 0;
		}

		if(vexRT[Btn6U] == 1)
		{
			motor[clawMotor] = 60;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[clawMotor] = -60;
		}
		else
		{
			motor[clawMotor] = 0;
		}
	}
	StartTask(stopAllMotors);
}
