#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    lineFollowerLEFT, sensorLineFollower)
#pragma config(Sensor, in3,    lineFollowerCENTER, sensorLineFollower)
#pragma config(Sensor, in4,    lineFollowerRIGHT, sensorLineFollower)
#pragma config(Sensor, in5,    armSensor,      sensorPotentiometer)
#pragma config(Sensor, in6,    lightSensor,    sensorNone)
#pragma config(Sensor, dgtl1,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           clawMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269, openLoop, reversed, encoder, encoderPort, dgtl1, 1000)
#pragma config(Motor,  port4,           neckMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port5,           rightMotor,    tmotorVex269, openLoop, encoder, encoderPort, dgtl3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task stopp()
{
	while(true){
		if(SensorValue[pushBtn] == 0 && vexRT[Btn7U] == 0)
		{
			StopAllTasks();
		}
	}
}

void stopMotors(){
	motor[rightMotor] = 0;
 	motor[leftMotor] = 0;
 	wait1Msec(1500);
}

void claw(int value){
	if(value == 60){
		motor[clawMotor] = 60;
		wait1Msec(1000);
	}
	else{
		motor[clawMotor] = -60;
		wait1Msec(1000);
	}
	motor[clawMotor] = 0;
}

void followLine()
{
	int threshold = 2600;
	int sonarSensorValue = 55; // 10
	while(true)
	{
		while(SensorValue(sonarSensor) > sonarSensorValue || SensorValue(sonarSensor) == -1)
		{
			if(SensorValue(lineFollowerRIGHT) > threshold)
			{
				// Steer right:
				motor[leftMotor]  = 50;
				motor[rightMotor] = 0;
			}

			if(SensorValue(lineFollowerCENTER) > threshold)
			{
				// Straight
				motor[leftMotor]  = 50;
				motor[rightMotor] = 50;
			}

			if(SensorValue(lineFollowerLEFT) > threshold)
			{
				// Steer left
				motor[leftMotor]  = 0;
				motor[rightMotor] = 50;
			}
		}
		if(SensorValue(sonarSensor) < 12)
		{
			break;
		}
	}
}

void turnaround()
{
	motor[leftMotor] = 60;
	motor[rightMotor] = -60;
	wait1Msec(1000);
}

task main()
{
	StartTask(stopp);
	
	claw(60);

	while(SensorValue(sonarSensor) > sonarSensorValue)
	{
		followLine();
	}

	stopMotors();

	claw(-60);

	while(SensorValue(armSensor) < 400)
	{
		motor[neckMotor] = -30;
	}
  	motor[neckMotor] = 0;

	turnaround();

	while(SensorValue(sonarSensor) > sonarSensorValue)
	{
		followLine();
	}

	stopMotors();

	while(SensorValue(armSensor) > 150)
	{
		motor[neckMotor] = 30;
	}
  	motor[neckMotor] = 0;

	claw(60);

	while(true){}
}